# Generated by Django 6.0.3 on 2026-04-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_user_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='title',
        ),
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default='default_tag', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.tags'),
        ),
    ]
